name: compiled-minicourse
channels:
  - conda-forge
dependencies:
  - python ==3.9
  - numpy >=1.20
  - matplotlib >=3
  - scipy >=1.2
  - jupyterlab >=2
  - plumbum >=1.6.9
  - numba >=0.50
  - pybind11 >=2.8
  - cython >=0.29.17
  - swig >=4
  - cppyy >=1.6
  - cffi >=1.14
  - compilers
  - cmake
  - ninja
  - nb_conda_kernels
  - mypy >=0.900
